### ISSUE TITLE
Let pinning also set page remembering?

### ISSUE THREAD

**Issue by Vampire** [pylorak/reloadmatic#11] opened 2017-11-24 16:06 UTC
This is probably more a question than an issue, or maybe a documentation issue.
I don't really understand what the setting mentioned in the title does or should do.

**Comment by pylorak** [comment] 2017-11-24 16:35
Hi! If that option is enabled, then when you pin a tab next time, ReloadMatic will turn on "Remember page" for that tab. And when you unpin one, it will disable that option. Of course Firefox must not be in incognito mode.

**Comment by pylorak** [comment] 2017-11-24 16:37
With different words: Pinning/unpinning is a Firefox feature, Remember Page is a ReloadMatic feature. This option lets the former automatically toggle the latter.

**Comment by Vampire** [comment] 2017-11-24 16:44
I understood that, but I have no idea what "Remember Page" should do, it is nowhere explained, or at least I didn't find it. Besides that, I tried to pin a tab and then looked at the settings page and below the checkbox at remembered pages nothing was displayed.

**Comment by pylorak** [comment] 2017-11-24 23:52
Remember Page is an option in the context menu that you can activate separately in each tab. When set, all the other settings set using the context menu will be stored and associated with the current URL. When you load the same page in the future, all your ReloadMatic settings will be restored, even in other tabs or after machine restarts.

**Comment by Vampire** [comment] 2017-11-25 22:25
Ah, I see, cool.
And I just found `faq.html` in the that explains it.
And now also that it is included and linked in the context menu.
Where the information maybe would be helpful too is the AMO page and the `More...` text in the add-on management page. :-)

**Comment by Vampire** [comment] 2017-11-25 22:42
And the `Remembered Pages` and the `Clear all` button in the add-on settings do not work. The auto-remember on pin works (checked in the context menu), but neither the auto-remember-on-pin, nor manual remembering adds the page to the settings section and pressing the `Clear all` button does not change anything, the page is still remembered according to the context menu.

**Comment by pylorak** [comment] 2017-12-03 11:46
True, the Clear all button seems to have some bug. Thy for letting me know. Fix queued for next version 1.5.1. auto-remember-on-pin does seem to work for me. Note that it only changes remember state for newly pinned/unpinned tabs, not for those that are already pinned, but this is on purpose. Maybe this is why you thought there is something wrong?

**Comment by Vampire** [comment] 2017-12-03 19:48
> Note that it only changes remember state for newly pinned/unpinned tabs, not for those that are already pinned, but this is on purpose.

I know that, but my statement still holds. I tested with newly pinned / unpinned tabs.

**Comment by pylorak** [comment] 2017-12-09 19:46
So do I understand correctly, that auto-remember-on-pin works for you? And your problem is that the page, when remembered, is not added to the settings page of the addon in a list? Note that remembered pages are not supposed to appear in the settings, there is no such list at all currently. The settings only has the "Clear all" button for remembered pages by design.

**Comment by Vampire** [comment] 2017-12-09 21:23
Oh, must have misunderstood then.
Somehow I expected the remembered pages to be listed there.
But even then, the "Clear all" button does not work properly.
If I press it, the state of remembered pages is not changed and even worse, the settings panel hangs. the other reloadmatic settings cannot be changed unless the page is left and returned to.

**Comment by pylorak** [comment] 2017-12-10 00:00
Yes that bug with the Clear All button really happens, but only on Windows, which is the reason I didn't notice it before releasing 1.5.0 because I develop on Linux, and there it works. Nevertheless, soon 1.5.1 will be release and it is fixed there and will work even on Windows.

**Comment by pylorak** [comment] 2017-12-10 00:47
1.5.1 is now released with the fix inside.

**Closed by pylorak** 2017-12-10 00:47 UTC
Labels: bug, question
